locale: fr

media_folder: 'public/img/articles'
public_folder: '/img/articles'

collections:
  - name: 'consommation'
    label: 'Consommation'
    folder: 'src/content/consommation'
    create: true
    delete: true
    slug: '{{slug}}'
    commit_message: '📢 Nouvel article : {{fields.title}} | {{fields.description}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Résumé', name: 'description', widget: 'text' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'logement'
    label: 'Logement'
    folder: 'src/content/logement'
    create: true
    delete: true
    slug: '{{slug}}'
    commit_message: '📢 Nouvel article : {{fields.title}} | {{fields.description}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Résumé', name: 'description', widget: 'text' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'conseils'
    label: 'Conseils'
    folder: 'src/content/conseils'
    create: true
    delete: true
    slug: '{{slug}}'
    commit_message: '📢 Nouvel article : {{fields.title}} | {{fields.description}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Résumé', name: 'description', widget: 'text' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
